### ISSUE TITLE
`getdof` depending on `with_logabsdet_jacobian`

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/MeasureBase.jl#102]
I just noticed this in the code:
```julia
# Assume that DOF are preserved if with_logabsdet_jacobian is functional:
@inline function getdof(ν::MU) where {MU<:PushforwardMeasure}
    T = Core.Compiler.return_type(testvalue, Tuple{typeof(ν.origin)})
    R = Core.Compiler.return_type(with_logabsdet_jacobian, Tuple{typeof(ν.f),T})
    _pushfwd_dof(MU, R, getdof(ν.origin))
end
```

Do we have any example where `getdof(v) = getdof(v.origin)` isn't enough?

I hear a lot of complaints about use of `return_type`. To me it's fine, as long as we only use it to help performance, as an implementation detail. It shouldn't influence the results of end users. I hear a lot of "`return_type` can always just return `Any`". So we should make sure having it return `Any` doesn't break anything.

All of that aside, why should this depend on `with_logabsdet_jacobian`?

**Comment by oschulz** [comment]
I think you're right, pushforward should always preserve DOF, I think we can simplify this as suggested.

**Comment by cscherrer** [comment]
Great! That was easier than I expected - thought I might be missing some subtlety.

It's such an easy change, I'll just close this and update dev. Thanks!
