### ISSUE TITLE
Depend on DiffRules

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/MeasureBase.jl#105]
ForwardDiff is heavy, but it allows defining simple rules in DiffRules, which is very light:
```julia
julia> @time_imports using DiffRules
     16.5 ms  IrrationalConstants
      1.3 ms  DiffRules
```

If MeasureBase depended on this, we could do e.g.
```julia
@define_diffrule MeasureBase.Φ(x) = :(logdensityof(StdNormal(), $x))
```

I think this would be easy to do for the `Std*` measures

**Comment by oschulz** [comment]
I'm not sure this will work, I think ForwardDiff only uses DiffRules for specific functions. I don't think this can generate method specializations for `ForwardDiff.Dual`.

**Comment by cscherrer** [comment]
Ahh, good to know. This stuff doesn't seem well-documented

**Comment by oschulz** [comment]
> This stuff doesn't seem well-documented

That's putting it mildly. :-)
