### ISSUE TITLE
Fix doc links

### ISSUE THREAD

**Issue by gdalle** [cscherrer/MeasureBase.jl#25]
Hi there! Is MeasureBase supposed to have its own documentation at some point? In the meantime, maybe the links in the README could redirect to that of MeasureTheory?

**Comment by cscherrer** [comment]
I had missed this, but we discussed. Updated in https://github.com/cscherrer/MeasureBase.jl/commit/cc80d4d2ed20624b1b4c0bff311811daf3808053
