### ISSUE TITLE
Changes in 0.6

### ISSUE THREAD

**Issue by theogf** [cscherrer/MeasureBase.jl#38]
Hey! It's great to see a new version, but the commit changelog is massive and I am a bit lost given that there are no deprecations :sweat_smile: 
In particular, what is the replacement for `For`?

**Comment by cscherrer** [comment]
Yeah, sorry it's a lot. Some pretty fundamental things weren't working great, so this was a big overhaul.

Looking back, the biggest changes are
- Moved `For` to MeasureTheory, to make MeasureBase lighter weight
- Separated support from log-density computations. So now `logdensityof` has to components: (1) compute `insupport`, and (2) compute `unsafe_logdensityof`
- Get rid of the `base_depth` stuff. @tkf had a nice suggestion here, that we could unroll things to some "deep enough" level to cover the cases we see in practice. This improved performance and simplified things a lot.

Also, `For` now has a lot more to it, but performance is much better. It's now `For{T,F,I}`, where `T` is the type of each component of the marginals. It's constructed as

```julia
@generated function For(f::F, inds::I) where {F,I<:Tuple}
    eltypes = Tuple{eltype.(I.types)...}
    quote
        $(Expr(:meta, :inline))
        T = Core.Compiler.return_type(f, $eltypes)
        For{T,F,I}(f, inds)
    end
end
```

**Comment by mschauer** [comment]
🙏 @tkf that’s nice

**Comment by cscherrer** [comment]
Here's the new code, I'm much happier with it:
```julia
@inline function logdensityof(μ, x)
    t() = dynamic(unsafe_logdensityof(μ, x))
    f() = -Inf
    ifelse(insupport(μ, x), t, f)()
end

# https://discourse.julialang.org/t/counting-iterations-to-a-type-fixpoint/75876/10?u=cscherrer
@inline function unsafe_logdensityof(μ::M, x) where {M}
    ℓ_0 = logdensity_def(μ, x)
    b_0 = μ
    Base.Cartesian.@nexprs 10 i -> begin  # 10 is just some "big enough" number
        b_{i} = basemeasure(b_{i-1})
        if b_{i} isa typeof(b_{i-1})
            return ℓ_{i-1}
        end
        ℓ_{i} = let Δℓ_{i} = logdensity_def(b_{i}, x)
            ℓ_{i-1} + Δℓ_{i}
        end
    end
    return ℓ_10
end
```

I've been using the idiom `ifelse(cond, t, f)()` lately, it's nice because it works when `cond` is a Bool or a StaticBool, but it still allows for lazy conditionals.
