### ISSUE TITLE
Using `ManifoldsBase`?

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/MeasureBase.jl#7]
From a Julia Slack DM with @sethaxen
![image](https://user-images.githubusercontent.com/1184449/130645023-1615c9df-d200-4acb-ae24-b634f9febf9f.png)

cc @mateuszbaran @kellertuer 

A super-lightweight dependency would be great, since that would help keep this package light :)

**Comment by cscherrer** [comment]
Currently, we only use `AbstractDomain` as a parameter for Lebesgue or Counting measure. So we just have a couple of functions for taking intervals and testing membership.

A secondary question to the OP is whether there's a benefit (to MeasureTheory, and/or to ManifoldMeasures) in having MeasureTheory depend on ManifoldsBase, in addition to any lightweight dependency to replace AbstractDomains

**Comment by kellertuer** [comment]
Currently we indeed do not have much support for non-Riemannian manifolds, but if you want we can surely go towards that, too, with the interface.
I am biased here, but I think the dependency would be nice, and since ManifoldsBase will stay lightweight, should be ok?

Sure we have to check for the R indicating the reals, I have no clue whether that would be over-engineering to have these three types in their own package...

**Comment by mateuszbaran** [comment]
We have some support for manifolds with just an affine connection. On the other hand, there are sampleable spaces that we are unlikely to ever support (for example spaces that are not locally Euclidean). Also note that currently Manifolds.jl is heavily skewed towards supporting embedded manifolds and we currently don't really support manifolds with boundaries (although that's a valid goal for us).

If all you need is testing membership then ManifoldsBase.jl doesn't look like the right abstraction.

**Comment by cscherrer** [comment]
Thanks all. The idea for doing this came from @sethaxen's mention of `Euclidean` in https://github.com/JuliaManifolds/ManifoldMeasures.jl/issues/14. We'll have some spaces that are not locally Euclidean, but I think the majority of them will be. And of course most of the manifold specifics should go in ManifoldMeasures. I'm just wondering, would it make things easier/harder for any/all of us to bring some of the very core functionality into MeasureTheory? For example,
1. Our `AbstractDomain` is kind of hacky, maybe changing it could make connecting these ecosystems more natural?
2. Lots of measures happen to be on a manifold, or a manifold with boundary at least. Would it help to "declare" this is MeasureTheory, even if we don't do much with that information until ManifoldMeasures?

**Comment by cscherrer** [comment]
Talking some more with @sethaxen, there may not be much advantage in this. We can reopen if this changes (or if I'm misunderstanding, which... let's not rule that out) , but for now let's instead consider https://github.com/cscherrer/MeasureBase.jl/issues/16
