### ISSUE TITLE
Callable densities

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/MeasureBase.jl#91]
Densities and log-densities (via `𝒹` and `log𝒹`, respectively) were originally callable. To me this was pretty elegant, allowing us to write tests like
```julia
         let d = ∫exp(log𝒹(Cauchy(), Normal()), Normal())
             @test logdensity_def(d, x) ≈ logdensity_def(Cauchy(), x) 
         end

         let f = log𝒹(∫exp(x -> x^2, Normal()), Normal())
             @test f(x) ≈ x^2
         end
```

With the introduction of DensityInterface.jl, we changed this, and started requiring the use of `logdensityof`. To me this is awkward and confusing. We get used to using `logdensityof` to get the log-density of a _measure_, but in this case we also use it to get the log-density of... a log-density?

In other cases, we also treat `logdensityof(m, x)` as equivalent to `logdensity_rel(m, rootmeasure(m), x)`. DensityInterface also breaks this idiom, since "root measure of a density" doesn't really make sense.

I think it's important to get back to a density being a callable function. Since some users might prefer the DensityInterface approach, let's try to make that available as well, maybe using it under the hood. 

See https://github.com/cscherrer/MeasureBase.jl/pull/85

**Comment by oschulz** [comment]
I'm fine with densities being callable. To solve the "log-of-log-densities" weirdness I would suggest that the result of `log𝒹(...)` should *not* support DensityInterface, it just return a "simple" function. The result of `𝒹(...)` should probably be a function that also supports DensityInterface.

Alternatively, both  `𝒹(...)` and `log𝒹(...)` could just return a "simple" function, and we would offer a separate function to get a "density object" (which would use `𝒹` and `log𝒹` internally to implement `densityof` and `logdensityof`. We could call it `relative_density(m, base)` or `rn_derivative(m, base)` or so. This might be the cleaner approach.

As for `logdensityof(m, x)` being equivalent to `logdensity_rel(m, rootmeasure(m), x)`, that should only be defined for measures, not for densities, I would say. One might argue that a likelihood ratio could be expressed this way (a density "relative" to another) but I don't think that should be covered by this API.

**Comment by cscherrer** [comment]
Fixed by https://github.com/cscherrer/MeasureBase.jl/pull/85
